import { Student } from "@/features/students/types/students.types";

export const students: Student[] = [
    {
        id: "1",
        name: "Julio",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "2",
        name: "María García",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "3",
        name: "Carlos López",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "4",
        name: "Ana Martínez",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "5",
        name: "Pedro Sánchez",
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "6",
        name: "Laura Rodríguez",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "7",
        name: "Diego Flores",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "8",
        name: "Sofia Torres",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "9",
        name: "Juan Ramírez",
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "10",
        name: "Elena Morales",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "11",
        name: "Miguel Ángel",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "12",
        name: "Valentina Costa",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "13",
        name: "Roberto Díaz",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "14",
        name: "Gabriela Ruiz",
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "15",
        name: "Fernando Ortiz",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "16",
        name: "Isabela Silva",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "17",
        name: "Andrés Gutiérrez",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "18",
        name: "Camila Navarro",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "19",
        name: "Lucas Vargas",
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "20",
        name: "Mariana Méndez",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    }
]